rev-1413 fixing pipeline

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -44,16 +44,18 @@ phases:
           initFilePath="NDATools/__init__.py"
           versionPattern="__version__ = '([0-9]+\.[0-9]+\.[0-9]+)'"
           initFileContent=$(cat "$initFilePath")
-          versionNumber=$(echo "$initFileContent" | grep -Po "$versionPattern" | cut -d"'" -f2)
           git push origin
-          if [ -n "$versionNumber" ]; then
-            echo "Version number found: $versionNumber"
-            gitTag="$versionNumber"
-            git tag "$gitTag"
-            git push --tags
-          else
-            echo "Version number not found in __init__.py"
-            exit 1
+          if [ "$ENV" = "prod" ]; then
+            versionNumber=$(echo "$initFileContent" | grep -Po "$versionPattern" | cut -d"'" -f2)
+            if [ -n "$versionNumber" ]; then
+              echo "Tagging version: $versionNumber"
+              gitTag="$versionNumber"
+              git tag "$gitTag"
+              git push --tags
+            else
+              echo "Version number not found in __init__.py"
+              exit 1
+            fi 
           fi
         else
           echo "SKIPPING PUSH TO GITHUB"
