Squashed commit of the following
commit 37576c3e 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 19:31:57 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - updating buildspec.yml


commit f5c952f7 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 19:30:27 GMT-0400 (Eastern Daylight Time) 

    Merge branch 'release/REV-1382-v0-5-0-release-for-nda-tools' into feature/REV-1413-fix-gh-sync

# Conflicts:
#	buildspec.yml


commit 60de43c9 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 19:28:20 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit e96cc176 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 19:20:24 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit a0bce8c3 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 16:27:29 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit 81f32756 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 15:52:10 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit 2c227f4b 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 15:44:34 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit 39a2b6d9 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 15:33:01 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit 11654d06 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 15:15:14 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit ae1f7358 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 15:07:33 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit 19147436 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 14:41:55 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit f7caa785 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 14:36:39 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit 12316fa3 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 13:29:39 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit fa3ef43e 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 13:25:55 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit ea4e6068 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 13:21:01 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit fce77ed0 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 13:15:35 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit c7b7c663 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 13:06:54 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit adaa0dc0 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 13:02:11 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit ee7c128c 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 12:57:36 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml


commit 89c0ec47 
Author: greg <greg.magdits@nih.gov> 
Date: Wed May 21 2025 12:04:57 GMT-0400 (Eastern Daylight Time) 

    rev-1413 - update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -13,9 +13,58 @@ phases:
       - pip install keyrings.alt
       - pip install -e '.[test]'
       - coverage run -m pytest && coverage report -m
-      - python -m build
-      - twine upload $PYTHON_ENV dist/* -u $PYPI_USER -p $TESTPYPI_PASSWORD
-      - $GITSCRIPT
+      - |
+        set -e
+        if [ -n "$PYPI_USER" ]; then
+          echo "building project ...."
+          python -m build
+          # set repository to testpypi if env variable TEST_PYPI is set
+          if [ -n "$PYPI_PASSWORD" ]; then
+            echo "Pushing to PyPI"
+            twine upload dist/* -u $PYPI_USER -p $PYPI_PASSWORD
+          elif [ -n "$TESTPYPI_PASSWORD" ]; then
+            echo "Pushing to Test PyPI"
+            twine upload dist/* -u $PYPI_USER -p $TESTPYPI_PASSWORD --repository-url https://test.pypi.org/legacy/        
+          else
+            echo "PYPI_PASSWORD not set"
+            exit 1
+          fi
+        else
+          echo "SKIPPING PUSH TO PYPI"
+        fi
+        if [ -n "$GITHUB_REPO" ]; then 
+          echo "Setting up SSH key"
+          mkdir -p ~/.ssh
+          echo "$SSH_PRIVATE_KEY" | tr "\t" "\n" > ~/.ssh/id_rsa
+          chmod 400 ~/.ssh/id_rsa
+          S3_URL=$(echo "$CODEBUILD_SOURCE_VERSION" | sed 's|arn:aws:s3:::|s3://|g')
+          echo "s3_url: $S3_URL"
+          BRANCH_NAME=$(aws s3 cp $S3_URL - | jq '.BranchName' | sed 's|"||g')
+          echo "BRANCH_NAME: $BRANCH_NAME"
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          git remote add github $GITHUB_REPO
+          echo "checking out $BRANCH_NAME"
+          git checkout $BRANCH_NAME
+          echo "pushing $BRANCH_NAME"
+          git push github "$BRANCH_NAME"
+          if [ "$ENV" = "prod" ]; then
+            echo "Extract the version number"
+            versionPattern="__version__ = '([0-9]+\.[0-9]+\.[0-9]+)'"
+            initFileContent=$(cat NDATools/__init__.py)
+            versionNumber=$(echo "$initFileContent" | grep -Po "$versionPattern" | cut -d"'" -f2)
+            if [ -n "$versionNumber" ]; then
+              echo "Tagging version: $versionNumber"
+              gitTag="$versionNumber"
+              git tag "$gitTag"
+              git push --tags
+            else
+              echo "Version number not found in __init__.py"
+              exit 1
+            fi
+          fi
+        else
+          echo "SKIPPING PUSH TO GITHUB"
+        fi
   post_build:
     commands:
       - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
